In [3]:
#11/3/22

In [4]:
#Unit 3-Regression
#Test,Train

In [14]:
#Linear data boston

In [6]:
import numpy as np

In [7]:
x=np.arange(10)
x


array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [9]:
X=x.reshape((5,2))
X

array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7],
       [8, 9]])

In [12]:
y=range(5)
type(y)

range

In [13]:
list(y)

[0, 1, 2, 3, 4]

In [42]:
from sklearn.model_selection import train_test_split

In [43]:
train_test_split(X,y,test_size=0.33,random_state=42)

[array([[4, 5],
        [0, 1],
        [6, 7]]),
 array([[2, 3],
        [8, 9]]),
 [2, 0, 3],
 [1, 4]]

In [44]:
X_train, x_test, Y_train, y_test = train_test_split(X, y, test_size=0.25, random_state=42)

In [45]:
X_train

array([[4, 5],
       [0, 1],
       [6, 7]])

In [46]:
x_test

array([[2, 3],
       [8, 9]])

In [47]:
Y_train

[2, 0, 3]

In [48]:
y_test

[1, 4]

In [49]:
X_train, x_test, Y_train, y_test = train_test_split(X, y, test_size=0.25)           #for accuracy 'random state' is required

In [50]:
X_train

array([[8, 9],
       [4, 5],
       [0, 1]])

In [52]:
x_test

array([[2, 3],
       [6, 7]])

In [53]:
Y_train

[4, 2, 0]

In [54]:
y_test

[1, 3]