In [2]:
#27-02-2022

In [11]:
list=["Sanjivani","COE","Kopargaon","Maharashtra"]
list1=[]
n=4

def filter_long_words(list,n):

    for i in list:
         s=len(i)
         if s>n:
            print(i)
            list1.append(i)
            print(list1)

In [12]:
filter_long_words(list,n)

Sanjivani
['Sanjivani']
Kopargaon
['Sanjivani', 'Kopargaon']
Maharashtra
['Sanjivani', 'Kopargaon', 'Maharashtra']


In [13]:
#Write python function which takes a character and returns true if it is an vowel and false if it not

In [1]:
def isvowel(ch):
    if ch in ["a","e","i","o","u","A","E","I","O","U"]:
        return "True"
    else:
        return "False"
a = input ("Enter the letter : ")
print (isvowel(a))

Enter the letter : a
True


In [3]:
!pip install numpy

In [4]:
import numpy as np
lst=[1,2,3,4]
type(lst)
a=np.array(lst)
type(a)
a.shape

(4,)

In [5]:
nested_lst=[[1,2,3],[4,5,6],[7,8,9],[10,11,12]]
type(nested_lst)
p=np.array(nested_lst)
type(p)

numpy.ndarray

In [6]:
p.shape

(4, 3)

In [7]:
p.reshape(2,6)

array([[ 1,  2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11, 12]])

In [8]:
p.reshape(2,8)

ValueError: cannot reshape array of size 12 into shape (2,8)

In [11]:
array=([[[1,2,3,4],[5,6,7,8],[9,10,11,12]]])


In [15]:
p.shape

(4, 3)

In [16]:
p.reshape(2,2,3)

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [17]:
np.array([1,2,3],dtype=float)

array([1., 2., 3.])

In [22]:
np.array([1.4,2,3], dtype=int)

array([1, 2, 3])

In [23]:
np.array([1,2,3],dtype=complex)

array([1.+0.j, 2.+0.j, 3.+0.j])

In [27]:
p[1:3][0:2]

array([[4, 5, 6],
       [7, 8, 9]])

In [30]:
p[1:3,1:3]

array([[5, 6],
       [8, 9]])

In [32]:
lst=([[1,2,3],[4,5,6],[7,8,9]])
p=np.array(lst)

In [33]:
p[1:3,0:2]

array([[4, 5],
       [7, 8]])

In [34]:
p[1:3,1:3]

array([[5, 6],
       [8, 9]])

In [35]:
type(np.mat([1,2,3,4]))

numpy.matrix

In [36]:
np.mat('1,2,3,4')

matrix([[1, 2, 3, 4]])

In [37]:
array1=np.array([12,34,5])
type(array1)

numpy.ndarray

In [38]:
array2=np.asarray([12,34,5])
type(array2)

numpy.ndarray

In [39]:
array3=np.asanyarray([12,34,5])
type(array3)

numpy.ndarray

In [40]:
#from function

a=np.fromfunction(lambda i,j:i==j,(3,3),dtype=int)

In [41]:
type(a)

numpy.ndarray

In [42]:
a

array([[ True, False, False],
       [False,  True, False],
       [False, False,  True]])

In [43]:
a=np.fromfunction(lambda i,j:i*j,(3,3),dtype=int)

In [44]:
a


array([[0, 0, 0],
       [0, 1, 2],
       [0, 2, 4]])

In [46]:
print(np.zeros(5))

[0. 0. 0. 0. 0.]


In [47]:
np.zeros((3,4,2))

array([[[0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.]],

       [[0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.]],

       [[0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.]]])

In [48]:
np.zeros((3,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [49]:
np.ones((5,2,8))

array([[[1., 1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1., 1.]],

       [[1., 1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1., 1.]],

       [[1., 1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1., 1.]],

       [[1., 1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1., 1.]],

       [[1., 1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1., 1.]]])

In [50]:
np.ones((10,3,5))

array([[[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]],

       [[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]],

       [[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]],

       [[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]],

       [[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]],

       [[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]],

       [[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]],

       [[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]],

       [[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]],

       [[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]]])

In [51]:
np.ones((3,5))*10

array([[10., 10., 10., 10., 10.],
       [10., 10., 10., 10., 10.],
       [10., 10., 10., 10., 10.]])

In [52]:
np.empty((3,5))           #Random values

array([[10., 10., 10., 10., 10.],
       [10., 10., 10., 10., 10.],
       [10., 10., 10., 10., 10.]])

In [53]:
#Identity matrix
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [54]:
print(np.linspace(4,8,80))                   #80:values between 4 to 8

[4.         4.05063291 4.10126582 4.15189873 4.20253165 4.25316456
 4.30379747 4.35443038 4.40506329 4.4556962  4.50632911 4.55696203
 4.60759494 4.65822785 4.70886076 4.75949367 4.81012658 4.86075949
 4.91139241 4.96202532 5.01265823 5.06329114 5.11392405 5.16455696
 5.21518987 5.26582278 5.3164557  5.36708861 5.41772152 5.46835443
 5.51898734 5.56962025 5.62025316 5.67088608 5.72151899 5.7721519
 5.82278481 5.87341772 5.92405063 5.97468354 6.02531646 6.07594937
 6.12658228 6.17721519 6.2278481  6.27848101 6.32911392 6.37974684
 6.43037975 6.48101266 6.53164557 6.58227848 6.63291139 6.6835443
 6.73417722 6.78481013 6.83544304 6.88607595 6.93670886 6.98734177
 7.03797468 7.08860759 7.13924051 7.18987342 7.24050633 7.29113924
 7.34177215 7.39240506 7.44303797 7.49367089 7.5443038  7.59493671
 7.64556962 7.69620253 7.74683544 7.79746835 7.84810127 7.89873418
 7.94936709 8.        ]


In [55]:
b=np.ones((4,5,2))

In [56]:
b.ndim

3

In [58]:
b.shape

(4, 5, 2)

In [59]:
b.dtype

dtype('float64')

In [60]:
np.arange(16)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

In [61]:
np.arange(16).ndim

1

In [62]:
np.arange(16).shape

(16,)

In [63]:
a=np.arange(16)
a.reshape(2,8)

array([[ 0,  1,  2,  3,  4,  5,  6,  7],
       [ 8,  9, 10, 11, 12, 13, 14, 15]])

In [64]:
a.reshape(2,8,1)

array([[[ 0],
        [ 1],
        [ 2],
        [ 3],
        [ 4],
        [ 5],
        [ 6],
        [ 7]],

       [[ 8],
        [ 9],
        [10],
        [11],
        [12],
        [13],
        [14],
        [15]]])

In [65]:
a.ndim

1

In [67]:
x=np.arange(16).reshape(-1,8)

In [68]:
np.diag(x)

array([0, 9])

In [69]:
np.diag(x,k=2)

array([ 2, 11])

In [70]:
np.diag(x,k=-1)

array([8])

In [ ]:
####################################